# Generated by Django 6.0 on 2025-12-06 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('privacy_read', models.CharField(choices=[('public', 'Público'), ('authenticated', 'Solo usuarios autenticados'), ('team', 'Solo usuarios del mismo equipo'), ('author', 'Solo el autor')], default='public', max_length=20)),
                ('privacy_write', models.CharField(choices=[('public', 'Público'), ('authenticated', 'Solo usuarios autenticados'), ('team', 'Solo usuarios del mismo equipo'), ('author', 'Solo el autor')], default='author', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
