# Generated by Django 6.0 on 2025-12-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_team_customuser_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='nombre',
            new_name='name',
        ),
    ]
