# Generated by Django 6.0 on 2025-12-10 16:45

import django.db.models.deletion
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_nombre_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.ForeignKey(default=user.models.get_default_team, on_delete=django.db.models.deletion.PROTECT, to='user.team'),
        ),
    ]
